driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    require_chef_omnibus: true
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box
- name: debian-7.2.0
  driver_config:
    require_chef_omnibus: true
    box: debian-7.2.0
    box_url: https://dl.dropboxusercontent.com/u/197673519/debian-7.2.0.box
- name: Debian8
  driver:
    box: debian/jessie64

suites:
- name: default
  run_list:
    - recipe[monit_bin::default]
  attributes:
    monit:
      version: 5.9
      monitrc:
        http_address: 127.0.0.1
